# Documentation about the configuration of Dependabot can be found in GitHub Docs
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2

updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
